### ISSUE TITLE
Simulation replay takes forever

### ISSUE THREAD

**Issue by mikel-zhobro** [eanswer/DiffHand#1]
Thank you for the great work! 

I am trying to get familiar with RedMaxDiff and noticed that rendering simulated trajectories takes forever (<=1 fps for hand-sphere).
Whereas, simulating itself is very fast (471 fps for hand-sphere and 10k+ fps for finger-torque). 

Is that normal? Am I doing something wrong?

Best, Mikel

**Comment by eanswer** [comment]
Hi MIkel,

That's abnormal. Did you just run the command suggested in the ReadMe? `python test_redmax.py --model hand_sphere`? The video gif posted in the ReadMe is the expected replay speed. 

Best,
Jie

**Comment by eanswer** [comment]
Are you using the `--record` flag? it takes a long time since it needs to save each frame image into the disk.

Best,
Jie

**Comment by mikel-zhobro** [comment]
hi @eanswer,
I tried both and it didn't change anything. Here is a gif with my replay speed:
![hand_sphere](https://user-images.githubusercontent.com/25222253/210738460-81bd7658-8af7-4de1-9769-d1bc03d38577.gif)

**Comment by mikel-zhobro** [comment]
Hi,
I apologize for the misleading issues. I just found out that I had some Nvidia drivers issues.
Best,
Mikel
