### ISSUE TITLE
Using this repository

### ISSUE THREAD

**Issue by OliEfr** [eanswer/DiffHand#5]
Hey,

I am interested in using this repo as well as your paper for our research.

Could you maybe provide a quickstart guide on how to run this code with a custom hand-configuration and custom skin-configuration. We would like to run the simulations using Isaac Sim / Gym for RL purposes.

Thanks and best,
Oliver

**Comment by eanswer** [comment]
Thanks for your interests in our code repo. A good starting point for building a customized hand configuration is to learn the interfaces through an existing example such as the [assemble task one](https://github.com/eanswer/DiffHand/blob/master/examples/DiffHand/rss_assemble/example_assemble.py). Basically, you need to build your own [robot xml file](https://github.com/eanswer/DiffHand/blob/master/assets/rss_two_finger_assemble.xml) and import the cage specifications. 

A simulation document is also attached [here](https://people.csail.mit.edu/jiex/papers/DiffHand/redmax_doc.pdf) to provide more mathematical details about the simulator, and might help you understand better the interfaces.

**Comment by OliEfr** [comment]
Thanks @eanswer for your quick reply!
Is the code in this repository used together with some physics simulator, such as Isaac-Gym, or should I use it standalone only?

**Comment by eanswer** [comment]
The codebase is self-contained including our own physics simulator DiffRedMax. To use Isaac-Gym, you need to convert the simulation config into Isaac Gym's.

**Comment by OliEfr** [comment]
Ok what file would that be?

Can we use your tactile skin simulation within Isaac? 

If not, do you by any chance another way to simulate a tactile skin in Isaac?

**Comment by eanswer** [comment]
Unfortunately not. This repo implements this [paper](http://people.csail.mit.edu/jiex/papers/TactileSim/index.html) and is the first such kind of simulator for efficiently simulating dense tactile field. To our best knowledge, there are no other existing simulators capable of doing this. If you really desire to use Isaac, there are two options: (1) using other tactile sensor representations to simulate tactile feedback, such as using [FEM](https://arxiv.org/pdf/2103.16747.pdf) that has been shown to work in Isaac; (2) implement our approach in Isaac Sim/Gym, our tactile model should be extensible to be implemented in any simulators.

**Comment by OliEfr** [comment]
Thats very interesting and thanks again for your help!

Might I ask, why you did not implement this algorithm for Isaac in the first place?

**Comment by eanswer** [comment]
You are welcome. (1) Isaac Sim is not open-sourced. (2) We developed our own simulator from scratch thus we are able to provide any flexibility to implement our tactile model.
